name: Juritech Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x] # Supported Node.js versions

    steps:
    - uses: actions/checkout@v3 # Checks-out your repository

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Caches npm modules

    - run: npm ci # Clean install of node dependencies

    # Run the build script if your project requires compilation or build step. If not needed, this can be removed.
    - run: npm run build --if-present

    # Run tests. Make sure you have a 'test' script in your package.json.
    - run: npm test
